# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs

##### using commands
commands:
    print_pipeline_id:
      parameters:
          id:
            type: string
      steps:
        - run: echo << parameters.id >>
        #- run: echo $CIRCLE_WORKFLOW_ID

#### using anchors
default: &dockerImage
  docker:
  - image: circleci/node:13.8.0


jobs:
  save_hello_world_output:
    << : *dockerImage
    steps:
      - run: echo "hello now" >  ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:      # file globs which will be persisted to the workspace
              - output.txt
  print_output_file:
    << : *dockerImage
    steps:
      - attach_workspace:
          at: ~/ # relative path to our working directory
      - run:
          command: |
           cat ~/output.txt
  test_command:
    << : *dockerImage
    steps:
      - print_pipeline_id:  
          id: << pipeline.id >> ##passing paramter to the command
      - run: 
          name: Running Special Command
          command: return 1
          shell: /bin/bash
      - run:
          name: Upload Failed Tests
          command: echo 'handle failed special command executed'
          when: on_fail
workflows:
  # Name the workflow "welcome"
  myworkflow:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - test_command